<a href="https://colab.research.google.com/github/dmontillao/ciencia-datos-curso/blob/main/tarea_01_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd


P1. Crea una variable llamada nombre con tu nombre, y otra llamada edad con tu edad.
Luego imprime el mensaje: Hola, me llamo Ana y tengo 22 años. (con tus datos).

In [23]:
nombre = "David"
edad = 34
print(f'Hola, me llamo {nombre} y tengo {edad} años')


Hola, me llamo David y tengo 34 años


P2. Dada la lista numeros = [10, 25, 3, 47, 8, 15]:

In [24]:
#Imprime el primer y el último elemento.
numeros = [10, 25, 3, 47, 8, 15]
print(numeros[0])
print(numeros[-1])

10
15


In [25]:
#Imprime los tres primeros elementos usando slicing.
print(numeros[0:3])

[10, 25, 3]


In [26]:
#Agrega el número 99 al final de la lista.
numeros.append(99)
print(numeros)

[10, 25, 3, 47, 8, 15, 99]


P3. Dado el diccionario estudiante con las llaves nombre, carrera y promedio,
escribe un if que imprima "Aprobado" si el promedio es mayor o igual a 6, y "Reprobado" si no.

In [29]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}
if estudiante["promedio"]>=6:
  print("Aprobado")
else:
  print("Reprobado")

Aprobado


P4. Crea una función llamada calcular_area que reciba base y altura y devuelva el área de un triángulo (base * altura / 2).
Llama la función con base=5 y altura=8 e imprime el resultado.

In [42]:
def Calcular_area(base, altura):
  area = (base* altura)/2
  return area


In [43]:
Calcular_area(3, 3)

4.5

P5. Usa una list comprehension para crear una lista con los cuadrados de los números del 1 al 10.
Imprime la lista resultante.

In [51]:
cuadrados = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
area_cuadrados = []

for x in cuadrados:
  area= (x * 4)
  area_cuadrados.append(area)
print(area_cuadrados)

[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]


P6. Crea los siguientes arreglos e imprime su shape y dtype:

In [58]:
#Un arreglo con los valores [1.5, 2.5, 3.5, 4.5]
lista = [1.5, 2.5, 3.5, 4.5]
array1 = np.array(lista)
print(array1, array1.shape, array1.dtype)

[1.5 2.5 3.5 4.5] (4,) float64


In [61]:
#Una matriz de ceros de 3 filas × 4 columnas
array2 = np.zeros((3, 4))
print(array2, array2.shape, array2.dtype)
#

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4) float64


In [62]:
# Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando linspace)
array3 = np.linspace(0, 1, 6)
print(array3, array3.shape, array3.dtype)


[0.  0.2 0.4 0.6 0.8 1. ] (6,) float64


In [80]:
#P7. Dado el arreglo a = np.arange(1, 13), usa reshape para convertirlo en una matriz de 3 × 4. Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.
a = np.arange(1, 13)
a = a.reshape(3, 4)
print(a)

maximo = a.max()
minimo = a.min()
print(f'el valor maximo es: {maximo} \n el valor minimo es: {minimo}')

print("posicion donde el valor es máximo:", np.where(a==maximo))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
el valor maximo es: 12 
 el valor minimo es: 1
posicion donde el valor es máximo: (array([2]), array([3]))


P8. Crea dos arreglos de 5 elementos con np.random.randint (valores entre 1 y 20).
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [88]:
array4 =np.random.randint(1, 20, 5)
array5 =np.random.randint(1, 20, 5)
print(array4)
print(array5)

suma = array4 + array5
resta = array4 - array5
multip = array4 * array5
division = array4 / array5

print(f'suma: {suma} \n resta: {resta} \n multiplicacion: {multip} \n division: {division}')

[ 5 15 13 15 17]
[16 16 10 10 11]
suma: [21 31 23 25 28] 
 resta: [-11  -1   3   5   6] 
 multiplicacion: [ 80 240 130 150 187] 
 division: [0.3125     0.9375     1.3        1.5        1.54545455]


P9. Dado el arreglo notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1]),
usa indexación booleana para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [90]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])
mascara = notas >= 6
resultado = notas[mascara]
print(resultado)

[ 8.5  6.   9.2  7.8 10. ]
